[package]
name = "worker-template"
version = "0.1.0"
authors = ["Ed Sweeney <navicore@gmail.com>"]
edition = "2024"
license = "MIT"

[lib]
crate-type = ["cdylib"]

[dependencies]
worker = "0.4"
serde = "1"
serde_json = "1"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
